namespace Integration.Shared.Domain;

/// <summary>
/// Supported operational alert types.
/// </summary>
public enum AlertType
{
    DeadLetter,
    CircuitBreaker,
    HighErrorRate,
    SapLoginFailed
}

/// <summary>
/// Severity of an operational alert.
/// </summary>
public enum AlertSeverity
{
    Warning,
    Critical
}

/// <summary>
/// Operational alert generated by the integration system.
/// Persisted in PostgreSQL for querying from the dashboard.
/// </summary>
public class IntegrationAlert
{
    public Guid Id { get; set; }
    public AlertType AlertType { get; set; }
    public AlertSeverity Severity { get; set; }
    public string TenantId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public string? Details { get; set; }
    public bool IsAcknowledged { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? AcknowledgedAt { get; set; }
    public string? AcknowledgedBy { get; set; }
}
